\set ON_ERROR_STOP on

DROP TABLE IF EXISTS transacciones CASCADE;
DROP TABLE IF EXISTS prestamos CASCADE;
DROP TABLE IF EXISTS cuentas CASCADE;
DROP TABLE IF EXISTS empleados CASCADE;
DROP TABLE IF EXISTS tipos_cuenta CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS sucursales CASCADE;

CREATE TABLE sucursales (
    id_sucursal integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) NOT NULL,
    ciudad varchar(80) NOT NULL,
    direccion varchar(150) NOT NULL
);

CREATE TABLE empleados (
    id_empleado integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(120) NOT NULL,
    cargo varchar(80) NOT NULL,
    salario numeric(12,2) NOT NULL CHECK (salario > 0),
    id_sucursal integer NOT NULL REFERENCES sucursales(id_sucursal)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE clientes (
    id_cliente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(80) NOT NULL,
    apellido varchar(80) NOT NULL,
    telefono varchar(20) NOT NULL,
    correo varchar(120) NOT NULL UNIQUE,
    ciudad varchar(80) NOT NULL
);

CREATE TABLE tipos_cuenta (
    id_tipo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion varchar(60) NOT NULL UNIQUE
);

CREATE TABLE cuentas (
    id_cuenta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta varchar(30) NOT NULL UNIQUE,
    saldo numeric(14,2) NOT NULL DEFAULT 0 CHECK (saldo >= 0),
    fecha_apertura date NOT NULL,
    estado varchar(30) NOT NULL CHECK (estado IN ('Activa', 'Bloqueada')),
    id_cliente integer NOT NULL REFERENCES clientes(id_cliente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    id_tipo integer NOT NULL REFERENCES tipos_cuenta(id_tipo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE transacciones (
    id_transaccion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo varchar(40) NOT NULL CHECK (tipo IN ('Deposito', 'Retiro', 'Transferencia')),
    monto numeric(14,2) NOT NULL CHECK (monto > 0),
    fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_cuenta integer NOT NULL REFERENCES cuentas(id_cuenta)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE prestamos (
    id_prestamo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto numeric(14,2) NOT NULL CHECK (monto > 0),
    tasa_interes numeric(5,2) NOT NULL CHECK (tasa_interes >= 0),
    fecha_inicio date NOT NULL,
    cuotas integer NOT NULL CHECK (cuotas > 0),
    id_cliente integer NOT NULL REFERENCES clientes(id_cliente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX idx_empleados_id_sucursal ON empleados(id_sucursal);
CREATE INDEX idx_cuentas_id_cliente ON cuentas(id_cliente);
CREATE INDEX idx_cuentas_id_tipo ON cuentas(id_tipo);
CREATE INDEX idx_transacciones_id_cuenta ON transacciones(id_cuenta);
CREATE INDEX idx_prestamos_id_cliente ON prestamos(id_cliente);
